<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZN5u7AH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZN5u7AH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZN5u7AH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZN5u7AH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZN5u7AH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZN5u7AH',
    'container.build_id' => 'c54191c8',
    'container.build_time' => 1582016137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZN5u7AH');
